### ISSUE TITLE
Molecule tests fail because of handlers

### ISSUE THREAD

**Issue by gluestix** [gluestix/ansible-role-teleport_client#3]
### The Issue

There is a task which calls two handlers, `Restart teleport` and `Start teleport` in `tasks/teleport.yml`:

```
- name: Copying over config file.
  ansible.builtin.template:
    src: default_teleport.yaml.j2
    dest: /etc/teleport.yaml
    owner: root
    group: root
    mode: '0600'
    force: true
  notify:
    - Restart teleport
    - Start teleport
```

Ansible calls them in the order in which they are defined in `handlers/main.yml`:

```
- name: Restart teleport
  become: true
  ansible.builtin.systemd:
    name: teleport.service
    state: restarted
    daemon_reload: true
    enabled: true

- name: Start teleport
  ansible.builtin.systemd:
    name: teleport.service
    state: started
    enabled: true
```

This leads to a situation where if the Teleport service does not restart fast enough, the start command will fail, as seen in CI workflow #14.  

### Possible Solution

Determine the state of Teleport prior to installation. If the service is running, then call restart. Else, call start.
